import hopsworks
import great_expectations as ge
from pathlib import Path
from helpers.utils import read_csv_folder
from helpers.config import HopsworksSettings
from helpers.transformations import GENERATION_MAPPING, entsoe_generation_transform

settings = HopsworksSettings(_env_file="./.env")
project = hopsworks.login(engine="python")


df_raw = read_csv_folder(
    Path("data/electricity-generation"), parse_datetime_cols=["Datetime (UTC)"]
)

gen_features = entsoe_generation_transform(df_raw.to_pandas())

gen_expectation_suite = ge.core.ExpectationSuite(
    expectation_suite_name="gen_expectation_suite"
)

# Add expectations for generation columns: values between 0 and 50000
for col in GENERATION_MAPPING:
    gen_expectation_suite.add_expectation(
        ge.core.ExpectationConfiguration(
            expectation_type="expect_column_values_to_be_between",
            kwargs={"column": col, "min_value": 0, "max_value": 50000, "mostly": 1.0},
        )
    )


fs = project.get_feature_store()

electricity_generation_fg = fs.get_or_create_feature_group(
    name="electricity_generation",
    description="Electricity generation for zones at time",
    version=1,
    primary_key=["zone_id"],
    event_time="datetime",
    expectation_suite=gen_expectation_suite,
)

electricity_generation_fg.insert(gen_features, wait=True)

electricity_generation_fg.update_feature_description(
    "datetime", "Date and time of electricity generation data point (utc)"
)
electricity_generation_fg.update_feature_description(
    "zone_id", "Id of the region the data point is valid for"
)
electricity_generation_fg.update_feature_description(
    "coal", "Electricity generated by coal in MW"
)
electricity_generation_fg.update_feature_description(
    "oil", "Electricity generated by oil in MW"
)
electricity_generation_fg.update_feature_description(
    "gas", "Electricity generated by gas in MW"
)
electricity_generation_fg.update_feature_description(
    "geothermal", "Electricity generated by geothermal in MW"
)
electricity_generation_fg.update_feature_description(
    "solar", "Electricity generated by solar in MW"
)
electricity_generation_fg.update_feature_description(
    "hydro", "Electricity generated by hydro in MW"
)
electricity_generation_fg.update_feature_description(
    "hydro_storage", "Electricity retrieved from hydro storage in MW"
)
electricity_generation_fg.update_feature_description(
    "wind", "Electricity generated by wind in MW"
)
electricity_generation_fg.update_feature_description(
    "biomass", "Electricity generated by biomass in MW"
)
electricity_generation_fg.update_feature_description(
    "battery_storage", "Electricity retrieved from battery storage in MW"
)
electricity_generation_fg.update_feature_description(
    "nuclear", "Electricity generated by nuclear in MW"
)
electricity_generation_fg.update_feature_description(
    "other", "Electricity generated by other sources in MW"
)
electricity_generation_fg.update_feature_description(
    "total", "Electricity generated by all sources in MW"
)